"use client";
import React from "react";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "../lib/AntdRegistry";

import { ConfigProvider, Layout } from "antd";

const { Header, Content } = Layout;

const layoutStyle: React.CSSProperties = {
  minHeight: "100vh",
  display: "flex",
  flexDirection: "column",
};

const headerStyle: React.CSSProperties = {
  boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.1)",
  zIndex: 0,
  backgroundColor: "#ffffff",
  fontWeight: "bold",
};

const contentStyle: React.CSSProperties = {
  flexGrow: 1,
  color: "#fff",
  backgroundColor: "#f7f7f7",
  margin: "0 100px",
};

import "./globals.css";
import theme from "../theme/themeConfig";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <Layout style={layoutStyle}>
            <Header style={headerStyle}>
              App title
            </Header>
            <Content style={contentStyle}>{children}</Content>
          </Layout>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
